(() => { 'use strict'; const STORAGE_KEY = 'app_language'; const DEFAULT_LANG = 'uz';
  const translations = {
    uz: { appTitle: 'Smart Byudjet Tracker', balance: 'Balans', income: 'Kirim', expense: 'Chiqim', startingBalance: "Boshlang'ich pul", transactions: 'Tranzaksiyalar', addTransaction: 'Tranzaksiya qoshish', category: 'Kategoriya', amount: 'Summa', note: 'Tavsif', date: 'Sana', save: 'Saqlash', cancel: 'Bekor qilish', edit: 'Tahrirlash', delete: "O'chirish", archive: 'Arxivlash', reset: "Ma'lumotlarni tozalash", language: 'Til', theme: 'Mavzu', dark: "Qorong'u", light: 'Yoriq', currency: 'Valyuta', profile: 'Profil', more: 'Yana', actions: 'Amallar', close: 'Yopish', noTransactions: "Hozircha tranzaksiyalar yo'q", kirim: 'Kirim', chiqim: 'Chiqim', type: 'Tur', selectType: 'Turing tanlang', selectCategory: 'Kategoriyani tanlang', today: 'Bugun', all: 'Barcha', settings: 'Sozlamalar', security: 'Xavfsizlik', reports: 'Hisobotlar', backupAndReset: 'Zaxira va tozalash', languageSelector: 'Til tanlang', themeSelector: 'Mavzu tanlang', currencySelector: 'Valyuta tanlang', backupExport: 'JSON eksport', backupImport: 'JSON import', resetData: "Ma'lumotlarni tozalash", resetWarning: 'Diqqat! Barcha ma\'lumotlar o\'chib ketadi.', resetCancel: 'Bekor qilish', resetConfirmBtn: 'Tozalash', exportSuccess: 'Eksport muvaffaqiyatli bajarildi', exportEmpty: "Eksport uchun ma'lumotlar yo'q", pdfTitle: 'Smart Byudjet - Hisobot', csvHeader: 'Sana,Turi,Kategoriya,Summa,Tavsif', unknown: "Noma'lum", other: 'Boshqa', food: 'Oziq-ovqat', transport: 'Transport', salary: 'Maosh', shopping: 'Xarid', utilities: 'Kommunal' },
    ru: { appTitle: 'Smart Budget Tracker', balance: 'Баланс', income: 'Доход', expense: 'Расход', startingBalance: 'Начальный баланс', transactions: 'Транзакции', addTransaction: 'Добавить транзакцию', category: 'Категория', amount: 'Сумма', note: 'Описание', date: 'Дата', save: 'Сохранить', cancel: 'Отмена', edit: 'Редактировать', delete: 'Удалить', archive: 'Архив', reset: 'Сброс данных', language: 'Язык', theme: 'Тема', dark: 'Темная', light: 'Светлая', currency: 'Валюта', profile: 'Профиль', more: 'Еще', actions: 'Действия', close: 'Закрыть', noTransactions: 'Нет транзакций', kirim: 'Доход', chiqim: 'Расход', type: 'Тип', selectType: 'Выберите тип', selectCategory: 'Выберите категорию', today: 'Сегодня', all: 'Все', settings: 'Настройки', security: 'Безопасность', reports: 'Отчеты', backupAndReset: 'Резервная копия и сброс', languageSelector: 'Выберите язык', themeSelector: 'Выберите тему', currencySelector: 'Выберите валюту', backupExport: 'Экспорт JSON', backupImport: 'Импорт JSON', resetData: 'Сброс данных', resetWarning: 'Внимание! Все данные будут удалены.', resetCancel: 'Отмена', resetConfirmBtn: 'Сброс', exportSuccess: 'Экспорт успешно completion', exportEmpty: 'Нет данных для экспорта', pdfTitle: 'Smart Budget - Отчет', csvHeader: 'Дата,Тип,Категория,Сумма,Описание', unknown: 'Неизвестно', other: 'Другое', food: 'Еда', transport: 'Транспорт', salary: 'Зарплата', shopping: 'Покупки', utilities: 'Коммуналка' },
    en: { appTitle: 'Smart Budget Tracker', balance: 'Balance', income: 'Income', expense: 'Expense', startingBalance: 'Starting Balance', transactions: 'Transactions', addTransaction: 'Add Transaction', category: 'Category', amount: 'Amount', note: 'Note', date: 'Date', save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete', archive: 'Archive', reset: 'Reset Data', language: 'Language', theme: 'Theme', dark: 'Dark', light: 'Light', currency: 'Currency', profile: 'Profile', more: 'More', actions: 'Actions', close: 'Close', noTransactions: 'No transactions yet', kirim: 'Income', chiqim: 'Expense', type: 'Type', selectType: 'Select type', selectCategory: 'Select category', today: 'Today', all: 'All', settings: 'Settings', security: 'Security', reports: 'Reports', backupAndReset: 'Backup & Reset', languageSelector: 'Select language', themeSelector: 'Select theme', currencySelector: 'Select currency', backupExport: 'Export JSON', backupImport: 'Import JSON', resetData: 'Reset Data', resetWarning: 'Warning! All data will be deleted.', resetCancel: 'Cancel', resetConfirmBtn: 'Reset', exportSuccess: 'Export completed', exportEmpty: 'No data to export', pdfTitle: 'Smart Budget - Report', csvHeader: 'Date,Type,Category,Amount,Note', unknown: 'Unknown', other: 'Other', food: 'Food', transport: 'Transport', salary: 'Salary', shopping: 'Shopping', utilities: 'Utilities' }
  };
  let currentLang = localStorage.getItem(STORAGE_KEY) || DEFAULT_LANG;
  function t(key) { return (translations[currentLang] && translations[currentLang][key]) || (translations[DEFAULT_LANG] && translations[DEFAULT_LANG][key]) || key; }
  function applyTranslations() { document.querySelectorAll('[data-i18n]').forEach(function(el) { var key = el.getAttribute('data-i18n'); if (key) el.textContent = t(key); }); document.querySelectorAll('[data-i18n-placeholder]').forEach(function(el) { var key = el.getAttribute('data-i18n-placeholder'); if (key) el.placeholder = t(key); }); }
  function setLanguage(lang) { if (!translations[lang]) return; currentLang = lang; localStorage.setItem(STORAGE_KEY, lang); applyTranslations(); if (window.updateDashboard) window.updateDashboard(); if (window.renderTransactions) window.renderTransactions(); if (window.renderArchivedPeriods) window.renderArchivedPeriods(); }
  window.translations = translations;
  window.t = t;
  window.setLanguage = setLanguage;
  window.getCurrentLang = function() { return currentLang; };
  document.addEventListener('DOMContentLoaded', function() { applyTranslations(); });
})();